name: Update Scoop Manifests

on:
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:

jobs:
  scoop-checkver:
    runs-on: windows-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Scoop
        uses: MinoruSekine/setup-scoop@v4

      - name: Update Manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          scoop config GH_TOKEN $env:GITHUB_TOKEN
          $bucketPath = $env:GITHUB_WORKSPACE
          scoop bucket add local $bucketPath
          $checkver = "$env:USERPROFILE\scoop\apps\scoop\current\bin\checkver.ps1"
          & $checkver * -u -dir $bucketPath

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          if (git status --porcelain) {
            git add freecad-weekly.json
            git commit -m "Auto-update: FreeCAD Weekly"
            git push
          } else {
            Write-Host "Keine Updates gefunden."
          }
